MovieLeague/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import logout

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'MovieLeague.views.home', name='home'),
    # url(r'^MovieLeague/', include('MovieLeague.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'', include('social_auth.urls')),

    (r'^$', 'league.views.home'),
    url(r'^league/(?P<league_id>\d*)/seasons', 'league.views.seasons', name="seasons"),
    url(r'^division/(?P<division_id>\d*)', 'league.views.division', name="division"),
    url(r'^season/(?P<season_id>\d*)', 'league.views.season', name="season"),
    url(r'^league/(?P<league_id>\d*)', 'league.views.league', name="league"),
    url(r'^team/(?P<team_id>\d*)', 'league.views.team', name="team"),
    url(r'^logout/(?P<next_page>.*)/$', logout, name="auth_logout"),
)

league/models.py
from django.contrib.auth.models import User
from django.db import models

import datetime


class Movie(models.Model):
    name = models.CharField(max_length=255)
    release_date = models.DateField()

    def _get_source_filtered_updates(self, source=None):
        if source:
            return self.moviegrossupdate_set.filter(source=source)
        return self.moviegrossupdate_set

    def get_value(self, source=None):
        source_filtered_updates = self._get_source_filtered_updates(source=source)
        if source_filtered_updates.count() > 0:
            return source_filtered_updates.latest().gross
        return 0

    def get_value_on_date(self, date, source=None):
        source_filtered_updates = self._get_source_filtered_updates(source=source)
        date_filtered_updates = source_filtered_updates.exclude(date__gt=date)
        if date_filtered_updates.count() > 0:
            return date_filtered_updates.latest().gross
        return 0

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['release_date']


class MovieExternalId(models.Model):
    movie = models.ForeignKey(Movie)
    source = models.TextField(max_length=32)
    identifier = models.TextField(max_length=255)


class MovieGrossUpdate(models.Model):
    movie = models.ForeignKey(Movie)
    date = models.DateField()
    gross = models.BigIntegerField()
    source = models.TextField(max_length=255)

    class Meta:
        get_latest_by = 'date'


class MovieMembership(models.Model):
    movie = models.ForeignKey(Movie)
    team = models.ForeignKey('Team')
    price = models.IntegerField()

    def value_on_team(self):
        end_date = self.team.division.season.end_date
        return self.movie.get_value_on_date(end_date)

    def efficiency(self):
        return self.value_on_team()/self.price

    class Meta:
        ordering = ['movie']


class League(models.Model):
    commissioner = models.ForeignKey(User, related_name='owned_leagues_set')
    players = models.ManyToManyField(User)
    name = models.TextField(max_length=50)
    short_description = models.TextField(max_length=50)
    long_description = models.TextField(max_length=255)

    def __unicode__(self):
        return self.name


class Season(models.Model):
    league = models.ForeignKey(League)
    start_date = models.DateField()
    end_date = models.DateField()
    name = models.TextField(max_length=100)
    movies = models.ManyToManyField(Movie)

    def has_ended(self):
        return datetime.date.today > self.end_date

    def _annotate_values(self, movie_list):
        annotated_movies = []
        for movie in movie_list:
            annotated_movies.append((movie, movie.get_value_on_date(self.end_date)))
        return annotated_movies

    def released_movies(self):
        return self._annotate_values(self.movies.exclude(release_date__gt=datetime.date.today()))

    def unreleased_movies(self):
        return self._annotate_values(self.movies.filter(release_date__gt=datetime.date.today()))

    def __unicode__(self):
        return self.name + ", " + str(self.start_date) + " to " + str(self.end_date)

    class Meta:
        get_latest_by = 'start_date'


class Division(models.Model):
    season = models.ForeignKey(Season)
    name = models.TextField(max_length=50)
    sort_order = models.PositiveSmallIntegerField()
    currency_unit = models.TextField(max_length=10)
    max_currency = models.IntegerField()
    num_relegated = models.SmallIntegerField()
    num_promoted = models.SmallIntegerField()

    def sorted_teams(self):
        return sorted(sorted(list(Team.objects.filter(division=self)), key=lambda x: x.get_team_cost()),
                      key=lambda x: x.get_team_value(), reverse=True)

    def get_leader(self):
        top_teams = self.sorted_teams()
        if len(top_teams) > 0:
            return top_teams[0]
        else:
            return None

    def is_relegation_enabled(self):
        return self.num_relegated > 0

    def is_promotion_enabled(self):
        return self.num_promoted > 0

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['sort_order']


class Team(models.Model):
    owner = models.ForeignKey(User)
    movies = models.ManyToManyField(Movie, through=MovieMembership)
    division = models.ForeignKey(Division)
    name = models.TextField(max_length=50, blank=True, null=True)

    def get_team_cost(self):
        cost = 0
        for movie_membership in self.moviemembership_set.all():
            cost += movie_membership.price
        return cost

    def get_team_value(self):
        value = 0
        for movie in self.movies.all():
            if movie.moviegrossupdate_set.count() > 0:
                value += movie.get_value_on_date(self.division.season.end_date)
        return value

    def get_team_value_for_date(self, date):
        value = 0
        for movie in self.movies.all():
            value += movie.get_value_on_date(date)
        return value

    def get_name(self):
        if self.name and len(self.name) > 0:
            return self.name
        else:
            return self.owner.username

    def get_position(self, reverse=False):
        sorted_division = self.division.sorted_teams()
        if reverse:
            sorted_division.reverse()
        position = sorted_division.index(self)
        return position

    def is_promoted(self):
        return self.get_position() < self.division.num_promoted

    def is_relegated(self):
        return self.get_position(reverse=True) < self.division.num_relegated

    def __unicode__(self):
        return self.get_name()

league/views.py
# Create your views here.
from django.shortcuts import render
from league.models import League, Team, Season, Division


def home(request):
    return render(request, 'home.html', {'leagues': League.objects.all()})


def league(request, league_id):
    requested_league = League.objects.get(id=league_id)
    latest_season = requested_league.season_set.latest()
    return render(request, 'league.html', {'league': requested_league, 'season': latest_season})


def team(request, team_id):
    requested_team = Team.objects.get(id=team_id)
    return render(request, 'team.html', {'team': requested_team, 'division': requested_team.division,
                                         'season': requested_team.division.season,
                                         'league': requested_team.division.season.league})


def seasons(request, league_id):
    requested_league = League.objects.get(id=league_id)
    return render(request, 'seasons.html', {'league': requested_league})


def season(request, season_id):
    requested_season = Season.objects.get(id=season_id)
    return render(request, 'season.html', {'season': requested_season, 'league': requested_season.league})


def division(request, division_id):
    requested_division = Division.objects.get(id=division_id)
    return render(request, 'division.html', {'division': requested_division, 'season': requested_division.season,
                                             'league': requested_division.season.league})

templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{{ STATIC_URL }}css/normalize.css">
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Oxygen:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/main.css">

    <!--[if IE 7]>
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome-ie7.min.css">
    <![endif]-->

    <script src="{{ STATIC_URL }}js/vendor/modernizr-2.6.2.min.js"></script>
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <!--[if lt IE 7]>
        <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    {% block header %}
        <div class="navbar navbar-static-top navbar-inverse">
            <div class="navbar-inner">
                <div class="container">
                    <h3>
                        {% if user.is_authenticated  %}
                            Welcome, {{ user.username }}! <a href="{% url "auth_logout" '/' %}">Logout</a>
                        {% else %}
                            Log in with: <a href="{% url "socialauth_begin" "facebook" %}"><img class="facebook-button" src="{{ STATIC_URL }}img/fb.png" /></a>
                        {% endif %}
                    </h3>
                </div>
            </div>
        </div>
    {% endblock %}
    <div id="content" class="container"><div class="row">
    {% block body %}{% endblock %}
    </div></div>

    <!-- Google Analytics -->
    <script>
        (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
        function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
        e=o.createElement(i);r=o.getElementsByTagName(i)[0];
        e.src='//www.google-analytics.com/analytics.js';
        r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
        ga('create','{{ GOOGLE_ANALYTICS_ID }}');ga('send','pageview');
    </script>
</body>
</html>

templates/division.html
{% extends "league.html" %}
{% load humanize %}
{% load league_filters %}
{% block content %}
    <ul class="nav nav-tabs">
        <li><a href="{% url "league" season.league.id %}">Home</a></li>
        <li><a href="{% url "seasons" season.league.id %}">Seasons</a></li>
    </ul>
    <div class="span8">
        <ul class="breadcrumb"><li><a href="{% url "seasons" season.league.id %}">Seasons</a><span class="divider">&gt;</span></li><li><a href="{% url "season" season.id %}">{{ season.name }}</a><span class="divider">&gt;</span></li><li>{{ division.name }}</li></ul>
        <h2>{{ division.name }}</h2>
        <ol>
        {% for team in division.sorted_teams %}
            <li><h3 {{ team|relegation|safe }}><a href="{% url "team" team.id %}">{{ team.get_name }}</a><span class="team-earnings pull-right"><small>{{ team|team_cost|safe }} for </small>${{ team.get_team_value|intcomma }}</span></h3>
                <h4>Movies</h4>
                <ul>
                    {% for movie_membership in team.moviemembership_set.all %}
                        <li><span class="movie-list">{{ movie_membership.movie.name }} <small class="muted">(Release Date: {{ movie_membership.movie.release_date|date }})</small><span class="pull-right muted"><small>{{ movie_membership|movie_membership_cost|safe }} for </small>${{ movie_membership.value_on_team|intcomma }}</span>
                            <p class="details">Efficiency: ${{ movie_membership.efficiency|intcomma }} per {{ team.division.currency_unit|safe }}</p>
                        </span></li>
                    {% endfor %}
                </ul>
            </li>
        {% endfor %}
        </ol>
    </div>
{% endblock %}
{% block sidebar %}
    <div class="span4">
        <h3>Division Settings</h3>
        <small class="muted">Currency: </small><p>{{ division.currency_unit|safe }}{{ division.max_currency }}</p>
        <small class="muted">Promotion: </small><p>{% if division.is_promotion_enabled %}Top {{ division.num_promoted }} team{{ division.num_promoted|pluralize }}{% else %}Disabled{% endif %}</p>
        <small class="muted">Relegation: </small><p>{% if division.is_relegation_enabled %}Bottom {{ division.num_relegated }} team{{ division.num_relegated|pluralize }}{% else %}Disabled{% endif %}</p>
        {% include "season_info.html" %}
    </div>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% block body %}
    <div class="span4">
    <h2>Leagues</h2>
    <ul>
    {% for league in leagues %}
        <li><a href="{% url "league" league.id %}">{{ league.name }}</a> <span class="muted pull-right">Commissioner: {{ league.commissioner.username }}</span></li>
    {% endfor %}
    </ul>
    </div>
    <div class="span4 offset4">This is the right side</div>
{% endblock %}

templates/league.html
{% extends "base.html" %}
{% load humanize %}
{% load league_filters %}
{% block body %}
    {% block herounit %}
        <div class="hero-unit">
            <h1>{{ league.name }}</h1>
            <h3><span class="muted">{{ league.short_description }}</span></h3>
        </div>
    {% endblock %}
    {% block content %}
        <ul class="nav nav-tabs">
            <li class="active"><a href="{% url "league" league.id %}">Home</a></li>
            <li><a href="{% url "seasons" league.id %}">Seasons</a></li>
        </ul>
        <div class="span8">
        <h2>Current Season</h2>
            <h3 class="muted">{{ league.season_set.latest.name }} ({{ league.season_set.latest.start_date|date }} to {{ league.season_set.latest.end_date|date }})</h3>
            {% include "season_standings.html" %}
        </div>
    {% endblock %}
    {% block sidebar %}
        <div class="span4">
            <h3>League Info</h3>
            <small class="muted">Commissioner: </small><p>{{ league.commissioner.username }}</p>
            <small class="muted">Description:</small><p>{{ league.long_description }}</p>
        </div>
    {% endblock %}
{% endblock %}

templates/season.html
{% extends "league.html" %}
{% load humanize %}
{% load league_filters %}
{% block content %}
    <ul class="nav nav-tabs">
        <li><a href="{% url "league" season.league.id %}">Home</a></li>
        <li><a href="{% url "seasons" season.league.id %}">Seasons</a></li>
    </ul>
    <div class="span8">
        <ul class="breadcrumb"><li><a href="{% url "seasons" season.league.id %}">Seasons</a><span class="divider">&gt;</span></li><li>{{ season.name }}</li></ul>
        <h2>{{ season.name }}</h2>
        {% include "season_standings.html" %}
    </div>
{% endblock %}
{% block sidebar %}
    <div class="span4">
        <h3>Season Info</h3>
        <small class="muted">Start Date: </small><p>{{ season.start_date|date }}</p>
        <small class="muted">End Date:</small><p>{{ season.end_date|date }}</p>
        {% include "season_info.html" %}
    </div>
{% endblock %}

templates/season_info.html
{% load humanize %}
<h3>Season Info</h3>
<small class="muted">Start Date: </small><p>{{ season.start_date|date }}</p>
<small class="muted">End Date:</small><p>{{ season.end_date|date }}</p>
<h3>Movies</h3>
<ul>
    {% for movie, value in season.released_movies %}
        <li>{{ movie.name }} <small class="muted">({{ movie.release_date|date }})</small> <small class="pull-right">${{ value|intcomma }}</small></li>
    {% endfor %}
</ul>
<div class="upcomingSeparator"><div></div><span>Upcoming</span></div>
<ul>
    {% for movie, value in season.unreleased_movies %}
        <li>{{ movie.name }} <small class="muted">({{ movie.release_date|date }})</small> <small class="pull-right">${{ value|intcomma }}</small></li>
    {% endfor %}
</ul>

templates/season_standings.html
{% load humanize %}
{% load league_filters %}
{% for division in season.division_set.all %}
    <h4><a href="{% url "division" division.id %}">{{ division.name }}</a></h4>
    <ol>
    {% for team in division.sorted_teams %}
        <li {{ team|relegation|safe }}><h4><a href="{% url "team" team.id %}">{{ team.get_name }}</a><span class="pull-right"><small class="muted">{{ division.currency_unit|safe }}{{ team.get_team_cost|intcomma }} for </small>${{ team.get_team_value|intcomma }}</span></h4></li>
    {% endfor %}
    </ol>
{% endfor %}

templates/seasons.html
{% extends "league.html" %}
{% load humanize %}
{% load league_filters %}
{% block content %}
    <ul class="nav nav-tabs">
        <li><a href="{% url "league" league.id %}">Home</a></li>
        <li class="active"><a href="{% url "seasons" league.id %}">Seasons</a></li>
	</ul>
    <div class="span8">
    <h2>Seasons</h2>
    {% for season in league.season_set.all %}
        <h4><a href="{% url "season" season.id %}">{{ season.name }}</a> ({{ season.start_date|date }} to {{ season.end_date|date }})</h4>
            <ul>
                {% for division in season.division_set.all %}
                    <li><a href="{% url "division" division.id %}">{{ division.name }}</a> <div class="muted">{% if season.has_ended %}Winner{% else %}Leader{% endif %}: {{ division.get_leader.get_name }} <span class="pull-right">{{ division.get_leader|team_cost|safe }} for ${{ division.get_leader.get_team_value|intcomma }}</span></div>
                    </li>
                {% endfor %}
            </ul>
    {% endfor %}
    </div>
{% endblock %}

templates/team.html
{% extends "league.html" %}
{% load humanize %}
{% block content %}
    <ul class="nav nav-tabs">
        <li><a href="{% url "league" season.league.id %}">Home</a></li>
        <li><a href="{% url "seasons" season.league.id %}">Seasons</a></li>
    </ul>
    <div class="span8">
        <ul class="breadcrumb"><li><a href="{% url "seasons" season.league.id %}">Seasons</a><span class="divider">&gt;</span></li><li>{{ season.name }}<span class="divider">&gt;</span></li><li>{{ division.name }}<span class="divider">&gt;</span></li>{{ team.owner.username }}'s Team</ul>
        <h2>{{ team.get_name }}</h2>
        <ul>
            {% for movie_membership in team.moviemembership_set.all %}
                <li><small class="muted">{{ movie_membership.movie.release_date|date }}</small>{{ movie_membership.movie.name }} &#8362;{{ movie_membership.price }} ${{ movie_membership.movie.get_value }}</li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}